package payouts

import (
	"context"
	"errors"
	"testing"
)

func TestPayoutAccountAndRequestFlow(t *testing.T) {
	svc := New()
	ctx := context.Background()

	account, err := svc.CreateAccount(ctx, CreateAccountRequest{
		TenantID:           "ten_01",
		PayoutAccountID:    "pa_01",
		OwnerProfileID:     "mp_exec_01",
		Provider:           "stripe",
		ProviderAccountRef: "acct_1",
		Jurisdiction:       "AU",
	})
	if err != nil {
		t.Fatalf("create account: %v", err)
	}
	if _, err := svc.GetAccount(ctx, "ten_01", account.PayoutAccountID); err != nil {
		t.Fatalf("get account: %v", err)
	}
	if len(svc.ListAccounts(ctx, "ten_01")) != 1 {
		t.Fatalf("expected one payout account in list")
	}

	payout, err := svc.RequestPayout(ctx, RequestPayoutRequest{
		TenantID:        "ten_01",
		PayoutID:        "po_01",
		PayoutAccountID: account.PayoutAccountID,
		EscrowID:        "escrow_1",
		Amount:          40,
		Currency:        "JWUSD",
		AutoComplete:    true,
	})
	if err != nil {
		t.Fatalf("request payout: %v", err)
	}
	if payout.Status != PayoutStatusCompleted {
		t.Fatalf("payout status=%q want %q", payout.Status, PayoutStatusCompleted)
	}
	if _, err := svc.GetPayout(ctx, "ten_01", payout.PayoutID); err != nil {
		t.Fatalf("get payout: %v", err)
	}
	if len(svc.ListPayouts(ctx, "ten_01")) != 1 {
		t.Fatalf("expected one payout in list")
	}
}

func TestPayoutErrorBranches(t *testing.T) {
	svc := New()
	ctx := context.Background()

	if _, err := svc.CreateAccount(ctx, CreateAccountRequest{
		TenantID:       "ten_01",
		OwnerProfileID: "mp_exec_01",
		Provider:       "stripe",
		Jurisdiction:   "AU",
	}); !errors.Is(err, ErrInvalidRequest) {
		t.Fatalf("expected invalid request for missing provider ref, got %v", err)
	}

	account, err := svc.CreateAccount(ctx, CreateAccountRequest{
		TenantID:           "ten_01",
		PayoutAccountID:    "pa_02",
		OwnerProfileID:     "mp_exec_01",
		Provider:           "stripe",
		ProviderAccountRef: "acct_2",
		Jurisdiction:       "ZZ",
	})
	if err != nil {
		t.Fatalf("create account: %v", err)
	}
	if _, err := svc.RequestPayout(ctx, RequestPayoutRequest{
		TenantID:        "ten_01",
		PayoutAccountID: account.PayoutAccountID,
		Amount:          10,
		Currency:        "JWUSD",
	}); !errors.Is(err, ErrInvalidRequest) {
		t.Fatalf("expected invalid jurisdiction error, got %v", err)
	}

	if _, err := svc.RequestPayout(ctx, RequestPayoutRequest{
		TenantID:        "ten_01",
		PayoutAccountID: "missing",
		Amount:          10,
		Currency:        "JWUSD",
	}); !errors.Is(err, ErrNotFound) {
		t.Fatalf("expected missing account error, got %v", err)
	}

	if _, err := svc.GetAccount(ctx, "ten_02", "pa_02"); !errors.Is(err, ErrNotFound) {
		t.Fatalf("expected tenant isolation not found for account, got %v", err)
	}
	if _, err := svc.GetPayout(ctx, "ten_01", "missing"); !errors.Is(err, ErrNotFound) {
		t.Fatalf("expected missing payout, got %v", err)
	}
}

func TestPayoutAutoIDsStatusesAndDuplicates(t *testing.T) {
	svc := New()
	ctx := context.Background()

	if _, err := svc.CreateAccount(ctx, CreateAccountRequest{
		TenantID:           "ten_01",
		PayoutAccountID:    "pa_bad_status",
		OwnerProfileID:     "mp_exec_01",
		Provider:           "stripe",
		ProviderAccountRef: "acct_bad",
		Jurisdiction:       "AU",
		Status:             "bad",
	}); !errors.Is(err, ErrInvalidRequest) {
		t.Fatalf("expected invalid account status error, got %v", err)
	}

	accountMeta := map[string]any{"kyc": "pending"}
	account, err := svc.CreateAccount(ctx, CreateAccountRequest{
		TenantID:           "ten_01",
		OwnerProfileID:     "mp_exec_01",
		Provider:           "stripe",
		ProviderAccountRef: "acct_auto",
		Jurisdiction:       "AU",
		Metadata:           accountMeta,
	})
	if err != nil {
		t.Fatalf("create account with auto id: %v", err)
	}
	if account.PayoutAccountID == "" {
		t.Fatalf("expected autogenerated payout account id")
	}
	accountMeta["kyc"] = "mutated"
	if account.Metadata["kyc"] != "pending" {
		t.Fatalf("expected metadata copy to be isolated, got %+v", account.Metadata)
	}

	payoutMeta := map[string]any{"attempt": 1}
	payout, err := svc.RequestPayout(ctx, RequestPayoutRequest{
		TenantID:        "ten_01",
		PayoutAccountID: account.PayoutAccountID,
		Amount:          12.5,
		Currency:        "jwusd",
		Metadata:        payoutMeta,
	})
	if err != nil {
		t.Fatalf("request payout with auto id: %v", err)
	}
	if payout.PayoutID == "" || payout.Status != PayoutStatusRequested {
		t.Fatalf("unexpected payout auto-id/status: %+v", payout)
	}
	if payout.Currency != "JWUSD" {
		t.Fatalf("expected normalized currency JWUSD, got %q", payout.Currency)
	}
	payoutMeta["attempt"] = 2
	if payout.Metadata["attempt"] != 1 {
		t.Fatalf("expected payout metadata copy, got %+v", payout.Metadata)
	}

	if _, err := svc.RequestPayout(ctx, RequestPayoutRequest{
		TenantID:        "ten_01",
		PayoutID:        "po_dup",
		PayoutAccountID: account.PayoutAccountID,
		Amount:          5,
		Currency:        "JWUSD",
	}); err != nil {
		t.Fatalf("first duplicate-id seed payout failed: %v", err)
	}
	if _, err := svc.RequestPayout(ctx, RequestPayoutRequest{
		TenantID:        "ten_01",
		PayoutID:        "po_dup",
		PayoutAccountID: account.PayoutAccountID,
		Amount:          6,
		Currency:        "JWUSD",
	}); !errors.Is(err, ErrAlreadyExists) {
		t.Fatalf("expected duplicate payout id error, got %v", err)
	}

	if len(svc.ListPayouts(ctx, "ten_01")) < 2 {
		t.Fatalf("expected at least two payouts in list")
	}
	if len(svc.ListPayouts(ctx, "ten_02")) != 0 {
		t.Fatalf("expected tenant isolated payout list")
	}
	if len(svc.ListAccounts(ctx, "ten_02")) != 0 {
		t.Fatalf("expected tenant isolated payout account list")
	}
}
